### ISSUE TITLE
No description?

### ISSUE THREAD

**Issue by keligijus** [TSmulkys/Mirkt#1]
😢 🆘 👎

**Comment by TSmulkys** [comment]
O kokio aprašymo reikia? Gi čia ne package. O, kas panaudota yra tinklapyje [Mirkt.lt/website-info](https://mirkt.lt/website-info)

**Comment by keligijus** [comment]
Rekomenduoju įdėt bent linką į veikiantį puslapį. Gi patogiau taip. Va, pull requestas tau https://github.com/TSmulkys/Mirkt/pull/2 :)
